spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dental
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    static-path-pattern: /images/**
  web:
    resources:
      static-locations: file:${user.dir}/src/main/resources/static/
  mail:
    host: smtp.qq.com
    port: 465
    username: 2912528586@qq.com
    password: zjaxvmblvcuedhag
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    protocol: smtp
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

uploadFilePath:
  doctorPicturesPath: ${user.dir}/src/main/resources/static/doctorPictures